name: Deploy Loomis Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🔹 Checkout repositório
        uses: actions/checkout@v3

      - name: 🔹 Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🔹 Instalar dependências
        run: npm install

      - name: 🔹 Build do projeto
        run: |
          chmod +x node_modules/.bin/vite
          npm run build

      - name: 🔹 Deploy no GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
